
"""SealDrop constants and bounded defaults.

These defaults intentionally favor conservative behavior over throughput.
"""

PACKAGE_EXTENSION = ".sdpkg"
PACKAGE_FORMAT_NAME = "sdpkg"
PACKAGE_MAGIC = b"SDPKGv1\n"
PACKAGE_VERSION = 1

HEADER_LENGTH_BYTES = 4
PAYLOAD_META_LENGTH_BYTES = 4
MAX_HEADER_BYTES = 64 * 1024
MAX_PAYLOAD_METADATA_BYTES = 32 * 1024

AES_KEY_BYTES = 32
AES_GCM_NONCE_BYTES = 12
KDF_SALT_BYTES = 16

KDF_NAME = "scrypt"
KDF_DEFAULT_N = 2**15
KDF_DEFAULT_R = 8
KDF_DEFAULT_P = 1
KDF_MIN_N = 2**14
KDF_MAX_N = 2**20
KDF_MIN_R = 1
KDF_MAX_R = 64
KDF_MIN_P = 1
KDF_MAX_P = 16

MIN_PASSPHRASE_BYTES = 12
MAX_INPUT_FILE_BYTES = 512 * 1024 * 1024

MAX_VISIBLE_NOTE_BYTES = 512

PAYLOAD_SCHEMA_VERSION = 1
CIPHER_NAME = "AES-256-GCM"
